import { FormEvent, useEffect, useState } from 'react';
import Layout from '@/components/layouts/admin';
import Card from '@/components/common/card';
import Button from '@/components/ui/button';
import { HttpClient } from '@/data/client/http-client';
import { adminOnly } from '@/utils/auth-utils';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { toast } from 'react-toastify';

type Kind = 'hero' | 'strip';
type Banner = { id?: number; kind: Kind; is_active: boolean; content: Record<string, any>; image?: File };
const heroContent = {background_type:'color',background_color:'#ffe72e',gradient_from:'#ff5bd7',gradient_to:'#304dff',gradient_angle:90,background_image:'',eyebrow:'SANCAN Маркет',eyebrow_color:'#111827',eyebrow_background:'#ffffff',title:'Цены напрямую от продавцов',title_color:'#000000',description:'Новые товары, подборки и выгодные предложения в одном каталоге.',description_color:'#3f3a16',button_one_text:'Промокод SANCAN',button_one_url:'#',button_one_color:'#111827',button_one_background:'#ffffff',button_two_text:'Скидки до 80%',button_two_url:'#',button_two_color:'#ffffff',button_two_background:'#8057ff',card_text:'Корзина сама себя не оплатит',card_badge:'%',card_note:'0+',card_background:'#8a65ff',card_text_color:'#ffffff'};
const stripContent = {background_type:'gradient',background_color:'#168cff',gradient_from:'#ef68d5',gradient_to:'#4255ff',gradient_angle:90,text:'РАСПРОДАЖА УЖЕ НАЧАЛАСЬ',text_color:'#ffffff',button_text:'Забрать сейчас',button_url:'#',button_color:'#ffffff',button_background:'#0b2548'};
const makeBanner=(kind:Kind):Banner=>({kind,is_active:true,content:{...(kind==='hero'?heroContent:stripContent)}});
const fields:Record<Kind,Array<[string,string]>>={hero:[['eyebrow','Надпись в плашке'],['title','Заголовок'],['description','Описание'],['button_one_text','Текст кнопки 1'],['button_one_url','Ссылка кнопки 1'],['button_two_text','Текст кнопки 2'],['button_two_url','Ссылка кнопки 2'],['card_text','Текст правой карточки'],['card_badge','Знак карточки'],['card_note','Метка карточки']],strip:[['text','Основной текст'],['button_text','Текст кнопки'],['button_url','Ссылка кнопки']]};
const colors:Record<Kind,Array<[string,string]>>={hero:[['background_color','Цвет фона'],['gradient_from','Градиент: начало'],['gradient_to','Градиент: конец'],['title_color','Цвет заголовка'],['description_color','Цвет описания'],['eyebrow_background','Фон плашки'],['eyebrow_color','Текст плашки'],['button_one_background','Фон кнопки 1'],['button_one_color','Текст кнопки 1'],['button_two_background','Фон кнопки 2'],['button_two_color','Текст кнопки 2'],['card_background','Фон карточки'],['card_text_color','Текст карточки']],strip:[['background_color','Цвет фона'],['gradient_from','Градиент: начало'],['gradient_to','Градиент: конец'],['text_color','Цвет текста'],['button_background','Фон кнопки'],['button_color','Текст кнопки']]};

export default function BannersPage(){
 const [banners,setBanners]=useState<Banner[]>([]),[autoplay,setAutoplay]=useState(true),[interval,setIntervalValue]=useState(5000),[saving,setSaving]=useState(false);
 useEffect(()=>{HttpClient.get<any>('/admin/homepage-banners').then(d=>{setBanners(d.banners?.length?d.banners:[makeBanner('strip'),makeBanner('hero')]);setAutoplay(d.autoplay);setIntervalValue(d.interval_ms);});},[]);
 const change=(i:number,key:string,value:any)=>setBanners(v=>v.map((b,n)=>n===i?{...b,content:{...b.content,[key]:value}}:b));
 const move=(i:number,delta:number)=>setBanners(v=>{const same=v.map((b,n)=>({b,n})).filter(x=>x.b.kind===v[i].kind),pos=same.findIndex(x=>x.n===i),target=same[pos+delta]?.n;if(target===undefined)return v;const copy=[...v];[copy[i],copy[target]]=[copy[target],copy[i]];return copy;});
 const submit=async(e:FormEvent)=>{e.preventDefault();setSaving(true);try{const d=new FormData();d.append('autoplay',autoplay?'1':'0');d.append('interval_ms',String(interval));banners.forEach((b,i)=>{if(b.id)d.append(`banners[${i}][id]`,String(b.id));d.append(`banners[${i}][kind]`,b.kind);d.append(`banners[${i}][is_active]`,b.is_active?'1':'0');Object.entries(b.content).forEach(([k,v])=>d.append(`banners[${i}][content][${k}]`,String(v??'')));if(b.image)d.append(`images[${i}]`,b.image);});await HttpClient.post('/admin/homepage-banners',d);toast.success('Баннеры сохранены');}catch(err:any){toast.error(err?.response?.data?.message||'Не удалось сохранить баннеры');}finally{setSaving(false);}};
 return <form onSubmit={submit} className="space-y-6"><Card><div className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-2xl font-bold">Баннеры главной</h1><p className="mt-1 text-sm text-body">Большой слайдер и узкая промо-полоса.</p></div><Button loading={saving}>Сохранить все</Button></div><div className="mt-6 flex flex-wrap gap-5"><label className="flex items-center gap-2 font-semibold"><input type="checkbox" checked={autoplay} onChange={e=>setAutoplay(e.target.checked)}/> Автопрокрутка</label><label className="font-semibold">Интервал, мс <input type="number" min="1500" max="60000" step="500" value={interval} onChange={e=>setIntervalValue(+e.target.value)} className="ml-2 w-28 rounded border p-2"/></label><button type="button" onClick={()=>setBanners(v=>[...v,makeBanner('hero')])} className="rounded bg-accent px-4 py-2 font-semibold text-white">+ Большой баннер</button><button type="button" onClick={()=>setBanners(v=>[...v,makeBanner('strip')])} className="rounded bg-gray-800 px-4 py-2 font-semibold text-white">+ Узкий баннер</button></div></Card>
 {banners.map((b,i)=><Card key={`${b.id||'new'}-${i}`}><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-bold">{b.kind==='hero'?'Большой баннер':'Узкий баннер'} #{banners.filter((x,n)=>x.kind===b.kind&&n<=i).length}</h2><div className="flex gap-2"><button type="button" onClick={()=>move(i,-1)} className="rounded border px-3 py-1">↑</button><button type="button" onClick={()=>move(i,1)} className="rounded border px-3 py-1">↓</button><button type="button" onClick={()=>setBanners(v=>[...v.slice(0,i+1),{...b,id:undefined,content:{...b.content}},...v.slice(i+1)])} className="rounded border px-3 py-1">Дублировать</button><button type="button" onClick={()=>setBanners(v=>v.filter((_,n)=>n!==i))} className="rounded border border-red-300 px-3 py-1 text-red-600">Удалить</button></div></div><label className="mb-5 flex items-center gap-2"><input type="checkbox" checked={b.is_active} onChange={e=>setBanners(v=>v.map((x,n)=>n===i?{...x,is_active:e.target.checked}:x))}/> Показывать на сайте</label>
 <div className="grid gap-5 lg:grid-cols-2"><div className="space-y-4"><label className="block font-semibold">Тип фона<select value={b.content.background_type} onChange={e=>change(i,'background_type',e.target.value)} className="mt-1 w-full rounded border p-3"><option value="color">Сплошной цвет</option><option value="gradient">Градиент</option>{b.kind==='hero'&&<option value="image">Изображение</option>}</select></label>{b.content.background_type==='gradient'&&<label className="block font-semibold">Направление градиента: {b.content.gradient_angle}°<input type="range" min="0" max="360" value={b.content.gradient_angle} onChange={e=>change(i,'gradient_angle',e.target.value)} className="mt-2 w-full"/></label>}{b.kind==='hero'&&b.content.background_type==='image'&&<label className="block font-semibold">Файл фона<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={e=>setBanners(v=>v.map((x,n)=>n===i?{...x,image:e.target.files?.[0]}:x))} className="mt-1 block w-full rounded border p-3"/></label>}<div className="grid grid-cols-2 gap-3">{colors[b.kind].map(([k,l])=><label key={k} className={`${k==='background_color'&&b.content.background_type!=='color'?'hidden':''} ${k.startsWith('gradient_')&&b.content.background_type!=='gradient'?'hidden':''} text-sm font-semibold`}>{l}<div className="mt-1 flex rounded border"><input type="color" value={b.content[k]||'#000000'} onChange={e=>change(i,k,e.target.value)} className="h-11 w-12"/><input value={b.content[k]||''} onChange={e=>change(i,k,e.target.value)} className="w-full px-2"/></div></label>)}</div></div><div className="space-y-3">{fields[b.kind].map(([k,l])=><label key={k} className="block text-sm font-semibold">{l}{k==='description'?<textarea value={b.content[k]||''} onChange={e=>change(i,k,e.target.value)} className="mt-1 w-full rounded border p-3"/>:<input value={b.content[k]||''} onChange={e=>change(i,k,e.target.value)} className="mt-1 w-full rounded border p-3"/>}</label>)}</div></div></Card>)}
 </form>;
}
BannersPage.authenticate={permissions:adminOnly};BannersPage.Layout=Layout;
export const getStaticProps=async({locale}:any)=>({props:{...(await serverSideTranslations(locale,['common','form','table']))}});
